apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ip-masq-agent
spec:
  template:
    spec:
      containers:
      - name: ip-masq-agent
        args:
            - --masq-chain=IP-MASQ
            # To non-masquerade reserved IP ranges by default, uncomment the line below.
            # - --nomasq-all-reserved-ranges
