# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
# This section includes base Calico installation configuration.
# For more information, see: https://projectcalico.docs.tigera.io/master/reference/installation/api#operator.tigera.io/v1.Installation
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
# we just let the Operator figure out the configuration
spec:
  variant: Calico
  registry: registry.sighup.io/fury/
  # Configures Calico networking.
  # calicoNetwork:
    # # Note: The ipPools section cannot be modified post-install.
    # ipPools:
      # - blockSize: 26
        # cidr: 192.168.0.0/16
        # encapsulation: VXLANCrossSubnet
        # natOutgoing: Enabled
        # nodeSelector: all()

# ---
# By default we don't deploy the API Server. If you need it / want it you can deploy it by uncommenting the definition below.
# This section configures the Calico API server.
# For more information, see: https://projectcalico.docs.tigera.io/master/reference/installation/api#operator.tigera.io/v1.APIServer
# apiVersion: operator.tigera.io/v1
# kind: APIServer
# metadata:
#   name: default
# spec: {}
