# Copyright (c) 2020 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

namespace: kube-system

bases:
  - dashboards

images:
  - name: calico/kube-controllers
    newTag: v3.16.1
  - name: calico/cni
    newTag: v3.16.1
  - name: calico/pod2daemon-flexvol
    newTag: v3.16.1
  - name: calico/node
    newTag: v3.16.1

resources:
- config.yml
- crd.yml
- deploy.yml
- ds.yml
- rbac.yml
- sm.yml
