# Copyright (c) 2020 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../katalog/calico

images:
  - name: registry.sighup.io/fury/calico/kube-controllers
    newName: calico/kube-controllers
  - name: registry.sighup.io/fury/calico/cni
    newName: calico/cni
  - name: registry.sighup.io/fury/calico/pod2daemon-flexvol
    newName: calico/pod2daemon-flexvol
  - name:  registry.sighup.io/fury/calico/node
    newName: calico/node